import graphviz
dot=graphviz.Digraph(comment='the round table',name="分支结构",node_attr={'shape':'box'})
dot.node('1','开始')
dot.node('2','请输入成绩=?', shape='parallelogram')
dot.node('3','x是否大等于90?', shape='diamond')
dot.node('4','x是否大等于80?', shape='diamond')
dot.node('5','x是否大等于70?', shape='diamond')
dot.node('6','x是否大等于60?', shape='diamond')
dot.node('a','Print A')
dot.node('b','Print B')
dot.node('c','Print C')
dot.node('d','Print D')
dot.node('e','Print E')
dot.node('7','结束')
dot.edges(['12','23','a7','b7','c7','d7','e7'])
dot.edge('3','a',label='Yes')
dot.edge('3','4',label='No')
dot.edge('4','b',label='Yes')
dot.edge('4','5',label='No')
dot.edge('5','c',label='Yes')
dot.edge('5','6',label='No')
dot.edge('6','d',label='Yes')
dot.edge('6','e',label='No')
dot